"""Config flags preamble"""

DEBUG := 1
; Feature Flips
ENABLE_DIALOG_SKIP := 1
ENABLE_INTRO := 1
ENABLE_VWF_ATTACK_NAMES := 1
BATTLE_ENABLED := 1
MAGIC_ENABLED := 1
ENABLE_KERNING := 1
ENABLE_KERNING_MENU := 1
ENABLE_BUTTON_DISPLAY := 1
BATTLE_CMD_VWF := 1
BATTLE_NAMES_VWF := 1
BATTLE_MONSTERS_VWF := 1
INVENTORY_ROLLING_BUFFER := 1
TREASURE_INVENTORY_ROLLING := 1  ; WIP, treasure rolling-buffer scaffolding only
TREASURE_DEBUG_ALWAYS_DROP := 1  ; force every win to drop an item (testing)
; Debug flags
TRIGGER_ENDING_CUTSCENE := 0
DEBUG_SHOW_ITEM_WINDOW := 0
ENABLE_BRK_HANDLER := 1
