.include 'src/ingame/main.s'
.include 'src/ingame/items.s'
.include 'src/ingame/options.s'
.include 'src/ingame/status.s'
.include 'src/ingame/magic.s'
.include 'src/ingame/shop.s'
.include 'src/ingame/equip.s'
