name: Nightly Release

on:
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Requirements
      if: steps.cache-requirements.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
    - name: Build patch
      run: ./build.py
    - name: Create Nightly Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly-${{ github.run_number }}
        name: Nightly Build ${{ github.run_number }}
        files: build/ff4.ips
        prerelease: true
        body: |
          Nightly build #${{ github.run_number }}
          
          Built from commit: ${{ github.sha }}
          
          This is an automated nightly build and may be unstable.